export const Banners = [
  { id: 1, imgUrl: "/aryapremierleague/angel.jpg" },
  { id: 2, imgUrl: "/Banners/2.jpeg" },
  { id: 3, imgUrl: "/Banners/3.jpeg" },
  { id: 4, imgUrl: "/Banners/4.jpeg" },
  { id: 5, imgUrl: "/Banners/5.jpeg" },
  { id: 6, imgUrl: "/Banners/6.jpeg" },
  { id: 7, imgUrl: "/Banners/7.jpeg" },
  { id: 8, imgUrl: "/Banners/8.jpeg" },
  { id: 9, imgUrl: "/Banners/9.jpeg" },
  { id: 10, imgUrl: "/Banners/10.jpeg" },
  { id: 11, imgUrl: "/Banners/11.jpeg" },
  { id: 12, imgUrl: "/Banners/12.jpeg" },
  { id: 13, imgUrl: "/Banners/13.jpeg" },
  { id: 14, imgUrl: "/Banners/14.jpeg" },
  { id: 15, imgUrl: "/Banners/15.jpeg" },
  { id: 16, imgUrl: "/Banners/16.jpeg" },
  { id: 17, imgUrl: "/Banners/17.jpeg" },
  { id: 18, imgUrl: "/Banners/18.jpeg" },
  { id: 19, imgUrl: "/Banners/19.jpeg" },
];
